sort:
  - name: What_is_TEA?
    path: What_is_TEA?/README.md
    children:
      - name: Fixing_a_Broken_Internet.md
      - name: How_TEA_Fixes_the_Internet.md
      - name: TEA_vs_IPFS.md
      - name: TEA_vs_Blockchain.md
      - name: TEA_vs_Trusted_Computing.md
      - name: TEA_vs_WASM.md
      - name: Use_Cases.md
  - name: Whitepaper
    path: Whitepaper/README.md
    children:
      - name: Legal_Disclaimer.md
      - name: Introduction.md
      - name: Problem_Statement.md
      - name: Our_Solution.md
      - name: TEA_Components.md
      - name: Tokenomics.md
      - name: Product_Roadmap.md
      - name: Appendix_A.md
      - name: Appendix_B.md
      - name: Bibliography.md
  - name: Blog_and_Vlog
    path: Blog_and_Vlog/README.md
    children:
      - name: Epoch_3_What_is_new.md
      - name: Bi-Weekly-Report-08-27-21.md
      - name: Bi-Weekly-Report-08-13-21.md
      - name: Bi-Weekly-Report-07-29-21.md
      - name: Gluon_yet_another_crypto_wallet.md
      - name: Can_trusted_computing_protect_your_digital_assets.md
      - name: Turn_ipfs_file_system_to_ipfs_function_service.md
      - name: Tea_at_the_Edge_taas_concept.md
      - name: TEA_Project_business_model.md
  - name: Try_the_demo
    path: Try_the_demo/README.md
    children:
      - name: Useful_Info_for_Miners.md
      - name: 202011_AI_demo.md
  - name: Under_the_hood
    path: Under_the_hood/README.md
    children:
      - name: Tea_on_layer1.md
      - name: Delegation_chain.md
      - name: Repin.md
      - name: Trust_chain.md
      - name: Easy_start.md
  - name: FAQ
    path: FAQ/README.md
    children:
      - name: Installing_Polkadot_Extension.md
      - name: Creating_a_New_Wallet_Account.md
      - name: Why_TEA_Dapps_Show_as_Not_Secure.md

  - name: 中文资料
    path: 中文资料/README.md
    children:
      - name: T计划简介
        path: /中文资料/chn_teaser.md
      - name: 代币经济学设计白皮书
        path: /中文资料/chn_token_economy.md
      - name: T计划和其他项目的主要区别
        path: /中文资料/chn_differences.md
      - name: T计划市场战略的三部曲
        path: /中文资料/go2market.md
      - name: T计划的矿工经济学
        path: /中文资料/miner_tokenomics.md
      - name: 挖矿竞赛简介(2.1赛季)
        path: /中文资料/mining_contest_epoch_2.1.md
      - name: 挖矿竞赛第三赛季预览
        path: /epoch3Preview.md
  # - name: 中文资料
  #   path: chn/README.md
  #   children:
  #     - name: chn_teaser
  #       path: /chn/chn_teaser.md
  #     - name: chn_token_economy
  #       path: /chn/chn_token_economy.md
  #     - name: chn_differences
  #       path: /chn/chn_differences.md


  # - name: test
  #   path: test/readme.md
  #   children:
  #     - name: aaa
  #       path: /test/a.md


