# This is a basic workflow to help you get started with Actions

name: Sync to jacky's tencent-1 server

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  Sync:
    name: Sync MD files to website server
    runs-on: ubuntu-latest 

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@main

      - name: Ssh login and Sync
        env: 
          id_rsa_pri: ${{ secrets.TOKEN_PRI }}
        run: |
          mkdir -p ~/.ssh/
          echo "$id_rsa_pri" > ~/.ssh/id_rsa 
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 81.70.96.136 >> ~/.ssh/known_hosts
          ssh ubuntu@81.70.96.136 "cd TEA/tea-docs && git pull"




